# Generated by Django 6.0.5 on 2026-05-29 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_geral', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fase do Processo',
                'verbose_name_plural': 'Fases dos Processos',
                'ordering': ['processo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('is_concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='processos.faseprocesso')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'ordering': ['fase', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=10)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='processos.itemchecklist')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('orgao', models.CharField(choices=[('PREFEITURA', 'Prefeitura'), ('BOMBEIROS', 'Bombeiros')], max_length=20)),
                ('categoria', models.CharField(choices=[('FUNCIONAMENTO', 'Funcionamento'), ('CONSTRUCAO', 'Construção'), ('SANITARIO', 'Sanitário')], default='FUNCIONAMENTO', max_length=20)),
                ('status', models.CharField(choices=[('EXCLUIDO', 'Excluído'), ('ATIVO', 'Ativo'), ('VENCENDO', 'Vencendo'), ('VENCIDO', 'Vencido'), ('CONCLUIDO', 'Concluído')], default='ATIVO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateField()),
                ('licenciamento_ambiental', models.BooleanField(default=False)),
                ('data_ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='clientes.empresa')),
                ('processos_relacionados', models.ManyToManyField(blank=True, related_name='processos_vinculados', to='processos.processo')),
                ('responsaveis', models.ManyToManyField(blank=True, related_name='processos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddField(
            model_name='faseprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='processos.processo'),
        ),
        migrations.CreateModel(
            name='Taxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paga', models.BooleanField(default=False)),
                ('is_isento', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxas', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Taxa',
                'verbose_name_plural': 'Taxas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Vistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('ADIADA', 'Adiada')], default='AGENDADA', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistorias', to='processos.processo')),
            ],
            options={
                'verbose_name': 'Vistoria',
                'verbose_name_plural': 'Vistorias',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['status', '-data_vencimento'], name='processos_p_status_f3c5f8_idx'),
        ),
        migrations.AddIndex(
            model_name='processo',
            index=models.Index(fields=['orgao', 'status'], name='processos_p_orgao_777a7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='faseprocesso',
            unique_together={('processo', 'nome')},
        ),
    ]
