# Generated by Django 6.0.5 on 2026-08-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='anexo',
            name='arquivo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
