# Generated by Django 6.0.5 on 2026-06-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='categoria',
            field=models.CharField(choices=[('FUNCIONAMENTO', 'Funcionamento'), ('CONSTRUCAO', 'Construção'), ('SANITARIO', 'Sanitário'), ('AMBIENTE', 'Licença Ambiental')], default='FUNCIONAMENTO', max_length=20),
        ),
    ]
