# Generated by Django 6.0.5 on 2026-09-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_remove_anexo_arquivo_anexo_arquivo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='categoria',
            field=models.CharField(choices=[('FUNCIONAMENTO', 'Funcionamento'), ('CONSTRUCAO', 'Construção'), ('SANITARIO', 'Sanitário'), ('AMBIENTAL', 'Licença Ambiental'), ('TRIBUTARIA', 'Tributária'), ('OUTRAS', 'Outras')], default='FUNCIONAMENTO', max_length=20),
        ),
    ]
