# Generated by Django 6.0.5 on 2026-06-06 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('categoria', models.CharField(choices=[('ALERTA_CRITICO', 'Alerta Crítico'), ('ALERTA', 'Alerta'), ('ATENÇÃO', 'Atenção'), ('AGENDAMENTO', 'Agendamento')], max_length=20)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('is_enviada_email', models.BooleanField(default=False)),
                ('data_envio_email', models.DateTimeField(blank=True, null=True)),
                ('is_lida', models.BooleanField(default=False)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='processos.processo')),
                ('usuarios_destinatarios', models.ManyToManyField(related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_geracao'],
                'indexes': [models.Index(fields=['categoria', '-data_geracao'], name='notificacoe_categor_7a15d7_idx'), models.Index(fields=['is_lida', '-data_geracao'], name='notificacoe_is_lida_c4a192_idx')],
            },
        ),
    ]
